### ISSUE TITLE
Screenshots Class - Is it implemented?

### ISSUE THREAD

**Issue by Drakonas** [Chadderz121/tcp-gecko-dotnet#6]
Sorry for making an issue for this, as it is vague, but I noticed the Screenshot code in the source and I'm wondering if it is implemented and how to use it? I don't see anything in the program for it.

Appreciate any help. Thanks.

**Comment by ghost** [comment]
No, it doesn't work for Wii U

**Comment by Drakonas** [comment]
Thank you.
